openapi: 3.0.0
info:
  title: User Management API
  description: ユーザ管理のAPI
  version: 1.0.0

paths:
#  /users/{uuid}:
#    $ref: "./paths/user.yml"
  /users/signup:
    $ref: "./paths/UserSignUp.yml"
  /users/signin:
    $ref: "./paths/UserSignIn.yml"