// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/gocraft/dbr/v2"
	"github.com/maooz4426/usermanager/infra/handler"
	"github.com/maooz4426/usermanager/infra/mysql"
	"github.com/maooz4426/usermanager/lib/usermanage"
	"github.com/maooz4426/usermanager/usecases"
)

// Injectors from wire.go:

func Wire(sess *dbr.Session) usermanage.ServerInterface {
	iUserRepository := mysql.NewUserRepository(sess)
	userUsecase := usecases.NewUserUsecase(iUserRepository)
	serverInterface := handler.NewHandler(userUsecase)
	return serverInterface
}
