development:
    dialect: mysql
    dir: ./migrations
    datasource: user:password@tcp(127.0.0.1)/db?parseTime=true
    table: migrations

ci:
    dialect: mysql
    dir: ./migrations
    datasource: root@tcp(127.0.0.1)/db?parseTime=true
    table: migrations