name: golangci-lint

on:
  push:
    branches:
    - develop
  pull_request:
    type:
      - opened
      - reopened
      - synchronize
    branches:
      - develop

jobs:
  lint:
    name: lint
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: setup for go
        uses: actions/setup-go@v5.1.0
        with:
          go-version-file: "./server/go.mod"
      - name: lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workdir: "./server"
          go_version_file: "go.mod"
          golangci_lint_flags: "--config=./config/.golangci.yml"
        


