name: Test and Build

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - develop

jobs:
  test:
    name: test
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: root
    steps:
      - name: install get_token
        id: get-token
        uses: getsentry/action-github-app-token@v3
        with:
          app_id: ${{ vars.APP_ID}}
          private_key: ${{ secrets.APP_PRIVATE_KEY}}
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: configure git for private key
        run: git config --global url."https://x-access-token:${{ steps.get-token.outputs.token }}@github.com".insteadOf "https://github.com"
      - name: Set up Go
        uses: actions/setup-go@v5.1.0
        with:
          go-version-file: './server/go.mod'
      - name: go mod tidy
        run: cd server && go mod tidy
      - name: install sql-migrate
        run: go install -v github.com/rubenv/sql-migrate/sql-migrate@latest
      - name: mysql wakeup
        run: |
          until( echo 'SELECT 1' |mysql -h 127.0.0.1 -P 3306 -uroot --silent &> /dev/null); do echo "waiting for mysql to be connectable" && sleep 2; done
      - name: migrate for tbls
        run: |
          mysql -h 127.0.0.1 -u root -e "CREATE DATABASE IF NOT EXISTS db DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin"
          sql-migrate up -env="development" -config="./server/config/db.config.yml"
      - name: install tbls
        uses: k1low/setup-tbls@v1
      - name: run tbls
        run: TBLS_DSN=mysql://root@localhost:3306/db tbls doc --rm-dist --config ./server/config/db.config.yml
      - name: fix tbls
        uses: dev-hato/actions-diff-pr-management@v1
        with:
          github-token: ${{ steps.get-token.outputs.token }}
          branch-name-prefix: fix-tbls

